var gulp = require('gulp')
var rename = require('gulp-rename')
var uglify = require('gulp-uglify')
var es = require('gulp-es6-transpiler')
gulp.task('js', ['transpiler'],function () {
  return gulp.src('dist/*.js')
  .pipe(uglify())
  .pipe(rename({extname: '.min.js'}))
  .pipe(gulp.dest('./resource'))
})
gulp.task('transpiler', function () {
  return gulp.src('./js/main.js')
  .pipe(es())
  .pipe(rename({extname: '.min.js'}))
  .pipe(gulp.dest('./resource/'))
})
gulp.task('default', ['transpiler','js'])
